name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-site:
    name: node-${{ matrix.node-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16, 18]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          package_json_file: site/package.json

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: site/pnpm-lock.yaml

      - name: Install
        run: pnpm run -C site install

      - name: Lint
        run: pnpm run -C site lint

      - name: Test
        run: pnpm run -C site test

      - name: Build
        run: pnpm run -C site build
